name: dev-poll-svc-pointable
on:
  pull_request:
    types: [open]
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: === INSTALL APP ===
        run: npm install
      - name: === TEST COVERAGE ===
        run: npm run test:coverage